config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :tasks

  root to: "projects#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :tasks, dependent: :destroy

    
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.includes(:tasks)
    @project = Project.new
    @tasks = @project.tasks
    @task = Task.new
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to root_path, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :set_project, only: [:show, :edit, :update, :destroy]

    def create 
        @task = Task.create(task_params)

        if @task.save
            redirect_to root_path, notice: 'Task was successfully created.' 
        else 
            redirect_to root_path
        end
    end

    def edit
    end
  
    def update 
        @task = Task.find(params[:id])

        if @task.update(task_params)
            redirect_to root_path, notice: 'Task was successfully updated.' 
        else 
            redirect_to root_path
        end
    end

    def destroy
        @task.destroy
        respond_to do |format|
          format.html { redirect_to root_path, notice: 'Task was successfully destroyed.' }
          format.json { head :no_content }
        end
      end

    private

    def set_project
        @task = Task.find(params[:id])
    end

    def task_params
        params.require(:task).permit(:name, :status, :project_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyGarage</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <div class="row mt-5 mb-5">
    <%= yield %>
    </div>
  </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_form_project.html.erb
<%= form_for @project, remote: true do |f| %>
<div class="d-flex align-items-center justify-content-center mb-2">
<span class="input-group-text m-0 rounded-0 border-right-0 rounded-left bg-primary text-light" id="basic-addon1">✚</span>
<div class="d-flex">
<%= f.text_field :name, class: "form-control rounded-0"%>
</div>
<div class="d-flex">
<%= f.submit "Add Project", class: "btn btn-primary rounded-0 rounded-right pl-2 pr-2" %>
</div></div>
<% end %>

app/views/projects/_tasks.html.erb
<% @tasks.each do |task|%>

<% if task.status == true %>
<strike>
<%= task.name%>
</strike>
<%= form_for task do |f| %>
<%= f.check_box :status, :value => task.status %>
<%= f.submit "Restore" %>
<% end %>
<% elsif task.status == false %>
<%= task.name%>
<%= form_for task do |f| %>
<%= f.check_box :status, :value => task.status %>
<%= f.submit "Done" %>
<% end %>
<% end %>

<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<!-- <%= notice %> -->
<ul class="list-group">
  <%= render "form_project"%>
  <% @projects.each do |project| %>
  <li class="list-group-item mb-3 border-0">

    <ul class="list-group">
      <li class="list-group-item list-group-item-warning">
        <div class="d-flex align-items-center justify-content-between">
          <strong class="text-dark"><span class="mr-4 ml-2">🗓 </span><%= project.name %></strong>
          <div class="h4 m-0">
            <%= link_to '✐', edit_project_path(project), class: "text-decoration-none text-muted" %>
            <span class="text-primary text-muted">&#160 |</span>
            <%= link_to '⌫', project, method: :delete, remote: true, data: { confirm: 'Are you sure?' }, class: "text-decoration-none ml-2 text-muted" %>
          </div>
        </div>
      </li>

      <li class="list-group-item list-group-item-secondary">
        <%= form_for @task, remote: true do |f| %>
        <div class="d-flex">
          <span class="input-group-text m-0 rounded-0 border-right-0 rounded-left bg-primary text-light"
            id="basic-addon1">✚</span>
          <div class="d-flex justify-content-start flex-fill">
            <%= f.text_field :name, class: "form-control rounded-0" %>
          </div>
          <div class="d-flex justify-content-start">
            <%= f.submit "Add Task", class: "btn btn-primary rounded-0 rounded-right pl-2 pr-2" %>
          </div>
        </div>
        <%= f.hidden_field :status, :value => false %>
        <%= f.hidden_field :project_id, :value => project.id %>
        <% end %>
      </li>

      <% project.tasks.each do |task| %>
      <% if task.status == true %>
      <li class="list-group-item list-group-item-success">
        <div class="d-flex align-items-center justify-content-end">
          <div class="d-flex mr-3">
            <%= form_for task, remote: true do |f| %>
            <%= f.hidden_field :status, :value => false %>
            <%= f.submit "↺", class: "btn btn-success" %>
          </div>
          <div class="d-flex">
            <em class="text-muted"><%= task.name %></em>
          </div>
          <div class="h6 m-0 d-flex ml-auto">
            <%= link_to '❖', root_path, class: "text-decoration-none text-muted" %>
            <span class="text-muted">&#160 | &#160</span>
            <%= link_to '✐', edit_project_path(project), class: "text-decoration-none text-muted" %>
            <span class="text-muted">&#160 |</span>
            <%= link_to '⌫', task, method: :delete, remote: true, data: { confirm: 'Are you sure?' }, class: "text-decoration-none ml-2 text-muted" %>
          </div>
        </div>
      </li>
      <% end %>
      <% elsif task.status == false %>
      <li class="list-group-item list-group-item-light">
        <div class="d-flex align-items-center">
          <div class="d-flex mr-3">
            <%= form_for task, remote: true do |f| %>
            <%= f.hidden_field :status, :value => true %>
            <%= f.submit "✓", class: "btn tn-secondary" %>
          </div>
          <div class="d-flex">
            <em><%= task.name %></em>
          </div>
          <div class="h6 m-0 d-flex ml-auto">
            <%= link_to '❖', root_path, class: "text-decoration-none text-muted" %>
            <span class="text-muted">&#160 | &#160</span>
            <%= link_to '✐', edit_task_path(task), class: "text-decoration-none text-muted" %>
            <span class="text-muted">&#160 |</span>
            <%= link_to '⌫', task, method: :delete, remote: true, data: { confirm: 'Are you sure?' }, class: "text-decoration-none ml-2 text-muted" %>
          </div>
        </div>
      </li>
      <% end %>
      <% end %>
      <% end %>

    </ul>
  </li>
  <% end %>
</ul>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', root_path %>